
# GitHub Actions workflow for deploying to k3s
name: Deploy to k3s

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install flask gunicorn

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config
  

      - name: Build and Push Docker Image
        run: |
          docker build -t siddeshwarsid/helloworld-py:latest .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push siddeshwarsid/helloworld-py:latest

      - name: Debug Network Connection to Kubernetes
        run: |
          curl -k https://10.0.1.216:6443/version
          nc -zv 10.0.1.216 6443

      - name: Verify Kubeconfig
        run: |
          kubectl config view
          kubectl get nodes
  
      - name: Deploy to k3s
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl rollout status deployment/helloworld
            
            
